apiVersion: v1
kind: PersistentVolume
metadata:
  name: ping-pv
  namespace: ping-ns
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  gcePersistentDisk:
    pdName: db-disk
    fsType: ext4
