apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pvc
  namespace: ping-ns
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
