apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.labels.app }}
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.service.labels.app }}
    spec:
      containers:
      - name: {{ .Values.service.labels.app }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.service.port }}
