{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-ping.serviceAccountName" . }}
  labels:
{{ include "flask-ping.labels" . | nindent 4 }}
{{- end -}}
