apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: ping-ns
  labels:
    app: ping-flask
spec:
  type: LoadBalancer
  ports:
  - name: flask
    port: 5000
    nodePort: 30002
    protocol: TCP
  selector:
    app: ping-flask
